; PlatformIO Project Configuration File
; Robot Diferencial ESP32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
;lib_deps =
;    adafruit/Adafruit MPU6050 @ ^2.2.4
;    adafruit/Adafruit VL53L0X @ ^1.2.4